name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1'

    - name: Install dependencies
      run: |
        sudo gem install cocoapods
        pod install

    - name: Build with Xcode
      run: xcodebuild -workspace LetsGo.xcworkspace -scheme LetsGo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' build

    - name: Run tests
      run: xcodebuild test -workspace LetsGo.xcworkspace -scheme LetsGo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14'
